url: http://kirbyt.github.io
baseurl: 

# Site Settings
title: Timeline of Melih Sahin
description: "The history of achievements of Melih, starting from 2022."
keywords: "jekyll, theme"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
